version: '3'
services:

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.6.2
        container_name: filebeat
        volumes: 
            - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./logs:/logs
            - ./configs/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
        # чтобы не сыпало ошибки на экран
        command: filebeat



    elk:
        image: sebp/elk:761
        container_name: elk
        environment: 
            # чтобы не запускать отдельные части change 1 to 0
            - LOGSTASH_START:1
            - ELASTICSEARCH_START:1
            - KIBANA_START:1
            # если есть ошибка при запуске elasticsearch
        #     - MAX_MAP_COUNT=262144
        
        # чтобы избавиться от SSL и сертификатов в filebeat
        # volumes: 
        #     - ./configs/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf

        ports:
            # kibana
            - "5601:5601"
            # elasticsearch
            - "9200:9200"
            # logstash
            - "5044:5044"    


networks:
    default:
        external:
            name: auth_proxy_network    